serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 12347
  path: /api/movies

loggerConfig:
  outputDir: ./logs/
  outputFile: test.log

databaseConfig:
  dbUsername: root
  dbPassword: password
  dbHostname: localhost
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: movies
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST


idmConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 12346
  path: /api/idm


idmEndpoints:
  privilege: /privilege
